"""engine

在 AgentScope 之上扩展的、类 LangGraph 的 Agent 图编排框架。

模块划分：
- ``constants``   : START / END 等哨兵节点。
- ``state``       : 图状态（GraphState）与状态归并器（reducer）。
- ``node``        : 节点抽象，可包裹 AgentScope agent、普通函数或子图。
- ``graph``       : 核心图引擎（StateGraph / CompiledGraph），仿照 LangGraph 语义。
- ``adapters``    : 将 AgentScope 的 ReActAgent 等封装为图节点。
- ``orchestrator``: 面向前端可视化的高层管理接口。
- ``server``      : 基于 FastAPI 的 REST 服务。
- ``failure``     : 失败轨迹数据结构（共享基础）。
- ``hooks``       : 执行钩子与钩子管理器（扩展点）。
- ``modules``     : 可插拔扩展模块（记忆 / 动态路由 / 流控 / 恢复策略 / 资源调度）。
"""

from .constants import START, END
from .state import GraphState, add_messages, append_reducer, replace_reducer
from .node import Node, NodeType
from .graph import StateGraph, CompiledGraph, GraphExecutionError
from .checkpoint import GraphCheckpoint, GraphCheckpointStore
from .orchestrator import Orchestrator, AgentSpec
from .failure import FailureRecord, FailureTrace, FAILURES_KEY
from .hooks import ExecutionHook, HookManager, NodeContext
from .modules.memory import (
    BGEM3EmbeddingModel,
    HashingEmbeddingModel,
    HybridTieredMemoryStore,
    MediaRoute,
    MemoryContext,
    MemoryItem,
    MemoryMedium,
    MemoryScope,
    MemoryStore,
    MemoryUpdateAction,
    OpenAIMemoryJudge,
    WakeupLevel,
    WakeupProfile,
    WakeupResult,
    wakeup_profile,
)
from .modules.context import (
    CONTEXT_LEDGER_KEY,
    CONTEXT_INJECTION_KEY,
    CONTEXT_INJECTION_TEXT_KEY,
    DRIFT_RESULT_KEY,
    BUDGET_PAUSED,
    PAUSE_REASON_KEY,
    RUN_STATUS_KEY,
    BudgetDecision,
    ContextBudget,
    ContextBudgetController,
    ContextCheckpoint,
    ContextCheckpointStore,
    ContextPolicy,
    ContextCompressor,
    ContextFact,
    ContextInjection,
    ContextInjector,
    DriftDetector,
    DriftResult,
    OpenAITaskDriftJudge,
    TaskDriftJudge,
    TaskDriftJudgeResult,
    ContextLedger,
    ContextLedgerRenderer,
    ContextLedgerStore,
    FailureSummary,
    TodoEvent,
    TodoItem,
    TodoManager,
    ToolSummary,
    rough_token_count,
)
from .modules.execution import (
    EdgeHttpExecutor,
    ExecutorRegistry,
    InferenceExecutor,
    InferenceRequest,
    InferenceResult,
    LocalEchoExecutor,
    LocalModelExecutor,
    OpenAICompatibleCloudExecutor,
    OpenAICompatibleExecutor,
    ResilientInferenceRunner,
)
from .modules.evaluation import EvaluationResult, Evaluator, RuleEvaluator
from .modules.security import (
    AuditPack,
    AuditPackBuilder,
    RedactionResult,
    SensitiveDataRedactor,
)
from .modules.scheduling import (
    AdaptiveResourceScheduler,
    AdvancedTrainingResult,
    BgeM3Encoder,
    EmbeddingClassifierRouter,
    HeuristicTaskGate,
    ModelSplitStep,
    LearnedTaskGate,
    OpenAITaskGate,
    RealtimeRequirement,
    ResourceAllocation,
    ResourceProfile,
    ResourceRequest,
    ResourceScheduler,
    ResourceStatus,
    ResourceTier,
    SchedulingDecision,
    SchedulingTrace,
    SensitivityLevel,
    MutableResourceMonitor,
    StaticResourceMonitor,
    SystemResourceMonitor,
    TaskComplexity,
    TaskGate,
    TaskProfile,
    RouteDataset,
    RouteExample,
    RouteTeacher,
    PseudoCascadeTeacher,
    BinaryTextRouterModel,
    benchmark_router,
    benchmark_embedding_router,
    benchmark_transformer_router,
    CascadeRouteDecision,
    FallbackCascadeTeacher,
    build_route_dataset,
    build_route_dataset_from_requests,
    default_training_texts,
    evaluate_gate,
    load_production_gate,
    desired_router_path,
    render_experiment_report,
    render_extended_experiment_report,
    RealCascadeTeacher,
    resolve_router_path,
    router_artifact_status,
    save_experiment_report,
    save_extended_experiment_report,
    train_bge_mlp_router,
    train_bge_router,
    TransformerTextRouter,
    train_router,
    train_transformer_router,
    ResourceMonitor,
    NoOpResourceMonitor,
    TrustedWorkspacePolicy,
)

__all__ = [
    "START",
    "END",
    "GraphState",
    "add_messages",
    "append_reducer",
    "replace_reducer",
    "Node",
    "NodeType",
    "StateGraph",
    "CompiledGraph",
    "GraphExecutionError",
    "GraphCheckpoint",
    "GraphCheckpointStore",
    "Orchestrator",
    "AgentSpec",
    # 失败轨迹
    "FailureRecord",
    "FailureTrace",
    "FAILURES_KEY",
    # 钩子
    "ExecutionHook",
    "HookManager",
    "NodeContext",
    # Memory
    "CONTEXT_LEDGER_KEY",
    "CONTEXT_INJECTION_KEY",
    "CONTEXT_INJECTION_TEXT_KEY",
    "DRIFT_RESULT_KEY",
    "BUDGET_PAUSED",
    "PAUSE_REASON_KEY",
    "RUN_STATUS_KEY",
    "BudgetDecision",
    "ContextBudget",
    "ContextBudgetController",
    "ContextCheckpoint",
    "ContextCheckpointStore",
    "ContextPolicy",
    "ContextCompressor",
    "ContextFact",
    "ContextInjection",
    "ContextInjector",
    "DriftDetector",
    "DriftResult",
    "OpenAITaskDriftJudge",
    "TaskDriftJudge",
    "TaskDriftJudgeResult",
    "ContextLedger",
    "ContextLedgerRenderer",
    "ContextLedgerStore",
    "FailureSummary",
    "TodoEvent",
    "TodoItem",
    "TodoManager",
    "ToolSummary",
    "rough_token_count",
    "BGEM3EmbeddingModel",
    "HashingEmbeddingModel",
    "HybridTieredMemoryStore",
    "MediaRoute",
    "MemoryContext",
    "MemoryItem",
    "MemoryMedium",
    "MemoryScope",
    "MemoryStore",
    "MemoryUpdateAction",
    "OpenAIMemoryJudge",
    "WakeupLevel",
    "WakeupProfile",
    "WakeupResult",
    "wakeup_profile",
    # Execution
    "EvaluationResult",
    "Evaluator",
    "RuleEvaluator",
    "EdgeHttpExecutor",
    "ExecutorRegistry",
    "InferenceExecutor",
    "InferenceRequest",
    "InferenceResult",
    "LocalEchoExecutor",
    "LocalModelExecutor",
    "OpenAICompatibleCloudExecutor",
    "OpenAICompatibleExecutor",
    "ResilientInferenceRunner",
    # Security
    "AuditPack",
    "AuditPackBuilder",
    "RedactionResult",
    "SensitiveDataRedactor",
    # Scheduling
    "AdaptiveResourceScheduler",
    "AdvancedTrainingResult",
    "BgeM3Encoder",
    "EmbeddingClassifierRouter",
    "HeuristicTaskGate",
    "LearnedTaskGate",
    "ModelSplitStep",
    "OpenAITaskGate",
    "RealtimeRequirement",
    "ResourceAllocation",
    "ResourceProfile",
    "ResourceRequest",
    "ResourceScheduler",
    "ResourceStatus",
    "ResourceTier",
    "SchedulingDecision",
    "SchedulingTrace",
    "SensitivityLevel",
    "MutableResourceMonitor",
    "StaticResourceMonitor",
    "SystemResourceMonitor",
    "TaskComplexity",
    "TaskGate",
    "TaskProfile",
    "RouteDataset",
    "RouteExample",
    "RouteTeacher",
    "PseudoCascadeTeacher",
    "BinaryTextRouterModel",
    "benchmark_router",
    "benchmark_embedding_router",
    "benchmark_transformer_router",
    "CascadeRouteDecision",
    "FallbackCascadeTeacher",
    "build_route_dataset",
    "build_route_dataset_from_requests",
    "default_training_texts",
    "evaluate_gate",
    "load_production_gate",
    "desired_router_path",
    "RealCascadeTeacher",
    "render_experiment_report",
    "render_extended_experiment_report",
    "resolve_router_path",
    "router_artifact_status",
    "save_experiment_report",
    "save_extended_experiment_report",
    "train_bge_mlp_router",
    "train_bge_router",
    "TransformerTextRouter",
    "train_router",
    "train_transformer_router",
    "ResourceMonitor",
    "NoOpResourceMonitor",
    "TrustedWorkspacePolicy",
]

__version__ = "0.1.0"
