"""可插拔扩展模块集合。

每个子模块提供接口（ABC）+ 空实现桩（NoOp / passthrough），便于独立开发：

- ``memory``     : 记忆模块（四级层级记忆读写与级联检索）。
- ``routing``    : 动态路由模块（静态 Router + 运行时 RoutingPolicy）。
- ``flow``       : 流控模块（依赖解析 + 条件激活，决定执行/跳过/延迟）。
- ``recovery``   : 恢复策略模块（依据失败轨迹决定修复路径）。
- ``scheduling`` : 端边云资源调度模块。
"""

from .memory import MemoryScope, MemoryContext, MemoryItem, MemoryStore, NoOpMemoryStore
from .context import (
    CONTEXT_LEDGER_KEY,
    CONTEXT_INJECTION_KEY,
    CONTEXT_INJECTION_TEXT_KEY,
    DRIFT_RESULT_KEY,
    BUDGET_PAUSED,
    PAUSE_REASON_KEY,
    RUN_STATUS_KEY,
    BudgetDecision,
    ContextBudget,
    ContextBudgetController,
    ContextCheckpoint,
    ContextCheckpointStore,
    ContextPolicy,
    ContextCompressor,
    ContextFact,
    ContextInjection,
    ContextInjector,
    DriftDetector,
    DriftResult,
    OpenAITaskDriftJudge,
    TaskDriftJudge,
    TaskDriftJudgeResult,
    ContextLedger,
    ContextLedgerRenderer,
    ContextLedgerStore,
    FailureSummary,
    TodoEvent,
    TodoItem,
    TodoManager,
    ToolSummary,
    rough_token_count,
)
from .routing import (
    RoutingDecision,
    Router,
    NoOpRouter,
    RoutingPolicy,
    PassthroughRoutingPolicy,
)
from .flow import FlowDecision, ActivationCondition, FlowController, NoOpFlowController
from .evaluation import EvaluationResult, Evaluator, RuleEvaluator
from .execution import (
    EdgeHttpExecutor,
    ExecutorRegistry,
    InferenceExecutor,
    InferenceRequest,
    InferenceResult,
    LocalEchoExecutor,
    OpenAICompatibleCloudExecutor,
    ResilientInferenceRunner,
)
from .recovery import (
    RecoveryAction,
    RecoveryAttempt,
    RecoveryEpisode,
    RecoveryPolicy,
    RepairPlan,
    RecoveryStrategy,
    NoOpRecoveryStrategy,
    PolicyRecoveryStrategy,
)
from .reasoning import (
    ConstraintIR, ConstraintKind, ConstraintViolation, Counterexample,
    DeterministicPlanGenerator, DeterministicPlanRepairer, LLMPlanGenerator,
    NeuroSymbolicReasoner, PlanGenerator, PlanIR, PlanRepairer, PlanRevision,
    ReasoningOutcome, SubtaskIR, SymbolicPlanValidator, ValidationResult,
    ValidationStatus,
)
from .fault_injection import FaultInjector, FaultSpec, InjectedFault
from .security import AuditPack, AuditPackBuilder, RedactionResult, SensitiveDataRedactor
from .scheduling import (
    AdaptiveResourceScheduler,
    HeuristicTaskGate,
    ModelSplitStep,
    OpenAITaskGate,
    RealtimeRequirement,
    ResourceProfile,
    ResourceStatus,
    ResourceTier,
    ResourceRequest,
    ResourceAllocation,
    ResourceScheduler,
    NoOpResourceScheduler,
    SchedulingDecision,
    SchedulingTrace,
    SensitivityLevel,
    MutableResourceMonitor,
    StaticResourceMonitor,
    SystemResourceMonitor,
    TaskComplexity,
    TaskGate,
    TaskProfile,
    ResourceMonitor,
    NoOpResourceMonitor,
    TrustedWorkspacePolicy,
)

__all__ = [
    # memory
    "CONTEXT_LEDGER_KEY",
    "CONTEXT_INJECTION_KEY",
    "CONTEXT_INJECTION_TEXT_KEY",
    "DRIFT_RESULT_KEY",
    "BUDGET_PAUSED",
    "PAUSE_REASON_KEY",
    "RUN_STATUS_KEY",
    "BudgetDecision",
    "ContextBudget",
    "ContextBudgetController",
    "ContextCheckpoint",
    "ContextCheckpointStore",
    "ContextPolicy",
    "ContextCompressor",
    "ContextFact",
    "ContextInjection",
    "ContextInjector",
    "DriftDetector",
    "DriftResult",
    "OpenAITaskDriftJudge",
    "TaskDriftJudge",
    "TaskDriftJudgeResult",
    "ContextLedger",
    "ContextLedgerRenderer",
    "ContextLedgerStore",
    "FailureSummary",
    "TodoEvent",
    "TodoItem",
    "TodoManager",
    "ToolSummary",
    "rough_token_count",
    "MemoryScope",
    "MemoryContext",
    "MemoryItem",
    "MemoryStore",
    "NoOpMemoryStore",
    # routing
    "RoutingDecision",
    "Router",
    "NoOpRouter",
    "RoutingPolicy",
    "PassthroughRoutingPolicy",
    # flow
    "EvaluationResult",
    "Evaluator",
    "RuleEvaluator",
    "FlowDecision",
    "ActivationCondition",
    "FlowController",
    "NoOpFlowController",
    # execution
    "EdgeHttpExecutor",
    "ExecutorRegistry",
    "InferenceExecutor",
    "InferenceRequest",
    "InferenceResult",
    "LocalEchoExecutor",
    "OpenAICompatibleCloudExecutor",
    "ResilientInferenceRunner",
    # recovery
    "RecoveryAction",
    "RepairPlan",
    "RecoveryStrategy",
    "NoOpRecoveryStrategy",
    "PolicyRecoveryStrategy", "RecoveryAttempt", "RecoveryEpisode", "RecoveryPolicy",
    "ConstraintIR", "ConstraintKind", "ConstraintViolation", "Counterexample",
    "DeterministicPlanGenerator", "DeterministicPlanRepairer", "LLMPlanGenerator",
    "NeuroSymbolicReasoner", "PlanGenerator", "PlanIR", "PlanRepairer",
    "PlanRevision", "ReasoningOutcome", "SubtaskIR", "SymbolicPlanValidator",
    "ValidationResult", "ValidationStatus", "FaultInjector", "FaultSpec", "InjectedFault",
    # security
    "AuditPack",
    "AuditPackBuilder",
    "RedactionResult",
    "SensitiveDataRedactor",
    # scheduling
    "AdaptiveResourceScheduler",
    "HeuristicTaskGate",
    "ModelSplitStep",
    "RealtimeRequirement",
    "ResourceProfile",
    "ResourceStatus",
    "ResourceTier",
    "ResourceRequest",
    "ResourceAllocation",
    "ResourceScheduler",
    "NoOpResourceScheduler",
    "OpenAITaskGate",
    "SchedulingDecision",
    "SchedulingTrace",
    "SensitivityLevel",
    "MutableResourceMonitor",
    "StaticResourceMonitor",
    "SystemResourceMonitor",
    "TaskComplexity",
    "TaskGate",
    "TaskProfile",
    "ResourceMonitor",
    "NoOpResourceMonitor",
    "TrustedWorkspacePolicy",
]
